In [ ]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
from IPython.display import display
import pandas as pd
from src.utils import *

In [2]:
# DATA = build_data_from_suffix("syntax")

pairs = {
    "full": ("str",     "ud"),
    "old":  ("str-old", "ud-old"),
    "new":  ("str-new", "ud-new"),
}

# Markup alignment

In [ ]:
from src.align_markup import align_markup

# align_markup(pairs)

In [4]:
ALIGNED = build_data_from_suffix("syntax", csv_dir="aligned")

# Error matrix

In [ ]:
from src.error_matrix import build_error_matrix
import dataframe_image as dfi

In [19]:
matrix_new = build_error_matrix(ALIGNED, "new")
head_new = 10
dfi.export(
    matrix_new.head(head_new),
    "error_matrix_new.png",
    table_conversion="matplotlib",
    dpi=300,
    fontsize=12,
)
matrix_new.head(head_new)

,,split,full,full_pct,old,old_pct,new,new_pct,total
deprel_g_str,deprel_g_ud,deprel_p_ud,,,,,,,
предик,nsubj:pass,nsubj,99,8.77,78,8.39,30,15.08,207
опред,acl,amod,48,4.52,29,3.63,17,6.44,94
аппоз,appos,flat:name,36,3.18,15,1.55,15,9.09,66
разъяснит,appos,parataxis,17,77.27,0,0.00,14,66.67,31
атриб,nmod,obl,71,2.49,56,2.46,11,1.90,138
обст,obl,nmod,58,1.18,40,1.02,7,0.68,105
огранич,fixed,advmod,20,13.33,4,4.44,6,10.00,30
аппоз,flat:name,appos,29,4.90,8,1.74,6,4.51,43
1-компл,obj,obl,149,2.88,30,0.82,6,0.40,185
вводн,vocative,parataxis,25,73.53,4,100.00,5,16.67,34

In [20]:
matrix_old = build_error_matrix(ALIGNED, "old")
head_old = 10
dfi.export(
    matrix_old.head(head_old),
    "error_matrix_old.png",
    table_conversion="matplotlib",
    dpi=300,
    fontsize=12,
)
matrix_old.head(head_old)

split                                 full  full_pct  old  old_pct  new  \
deprel_g_str deprel_g_ud deprel_p_ud
предик       nsubj:pass  nsubj          99      8.77   78     8.39   30
атриб        nmod        obl            71      2.49   56     2.46   11
1-компл      obl         obj           109      3.31   55     2.07    4
обст         obl         nmod           58      1.18   40     1.02    7
примыкат     appos       parataxis      44     80.00   37    71.15    0
1-компл      obj         obl           149      2.88   30     0.82    6
опред        acl         amod           48      4.52   29     3.63   17
сравнит      obl         advcl          17      7.46   21    12.65    0
аппоз        appos       flat:name      36      3.18   15     1.55   15
                         nmod           18      1.59   12     1.24    4

split                                 new_pct  total
deprel_g_str deprel_g_ud deprel_p_ud
предик       nsubj:pass  nsubj          15.08    207
атриб        nmod        obl             1.90    138
1-компл      obl         obj             0.62    168
обст         obl         nmod            0.68    105
примыкат     appos       parataxis       0.00     81
1-компл      obj         obl             0.40    185
опред        acl         amod            6.44     94
сравнит      obl         advcl           0.00     38
аппоз        appos       flat:name       9.09     66
                         nmod            2.42     34

In [21]:
matrix_full = build_error_matrix(ALIGNED, "full")
head_full = 10
dfi.export(
    matrix_full.head(head_full),
    "error_matrix_full.png",
    table_conversion="matplotlib",
    dpi=300,
    fontsize=12,
)
matrix_full.head(head_full)

split                                 full  full_pct  old  old_pct  new  \
deprel_g_str deprel_g_ud deprel_p_ud
1-компл      obj         obl           149      2.88   30     0.82    6
             obl         obj           109      3.31   55     2.07    4
предик       nsubj:pass  nsubj          99      8.77   78     8.39   30
количест     nummod:gov  nummod         77     24.52    7     4.07    2
атриб        nmod        obl            71      2.49   56     2.46   11
сравн-союзн  case        mark           61     93.85    3    60.00    0
обст         obl         nmod           58      1.18   40     1.02    7
присвяз      xcomp       obl            54     76.06    5    50.00    0
опред        acl         amod           48      4.52   29     3.63   17
1-компл      xcomp       obl            48      3.53    6     0.62    0

split                                 new_pct  total
deprel_g_str deprel_g_ud deprel_p_ud
1-компл      obj         obl             0.40    185
             obl         obj             0.62    168
предик       nsubj:pass  nsubj          15.08    207
количест     nummod:gov  nummod          1.41     86
атриб        nmod        obl             1.90    138
сравн-союзн  case        mark            0.00     64
обст         obl         nmod            0.68    105
присвяз      xcomp       obl             0.00     59
опред        acl         amod            6.44     94
1-компл      xcomp       obl             0.00     54